export type Crop = { x: number; y: number; w: number; h: number };
export type Layout = 'one_media' | 'two_cameras' | 'two_media';
export type MediaTransform = { fit:'contain'|'cover'; zoom:number; x:number; y:number };
export type Project = {
  id: string;
  status: string;
  import_stage?: string;
  import_error?: string;
  original_name: string;
  source_url?: string;
  preview_file: string;
  metadata: { duration: number; width: number; height: number; fps: string };
  transcript_status: string;
  transcript_error?: string;
  transcript_hint?: string;
  transcript_source?: string;
  media?: Media[];
  renders?: RenderItem[];
};
export type Media = { id: string; file: string; name: string; type: 'image' | 'video'; source_url?: string };
export type RenderItem = { id: string; file: string; start: number; end: number; layout: Layout };
export type SearchResult = { start: number; end: number; text: string; score: number };
